package com.pulsefit.subscription;
import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.client.RestClient;
@RestController @RequestMapping("/api/subscriptions") public class SubscriptionController { private final PlanRepository plans; private final SubscriptionRepository subs; private final RestClient.Builder rb; public SubscriptionController(PlanRepository p,SubscriptionRepository s,RestClient.Builder b){plans=p;subs=s;rb=b;}
 @GetMapping("/plans") public List<Plan> plans(){return plans.findAll();}
 @PostMapping("/plans") public ResponseEntity<Plan> createPlan(@RequestBody Plan p){return ResponseEntity.status(201).body(plans.save(p));}
 @GetMapping("/{id}") public ResponseEntity<Subscription> get(@PathVariable Long id){return subs.findById(id).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());}
 @GetMapping("/member/{memberId}") public List<Subscription> byMember(@PathVariable Long memberId){return subs.findByMemberId(memberId);}
 @GetMapping("/member/{memberId}/active") public ResponseEntity<?> active(@PathVariable Long memberId){return subs.findFirstByMemberIdAndStatusOrderByEndDateDesc(memberId,"ACTIVE").filter(s->!s.getEndDate().isBefore(LocalDate.now())).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());}
 @GetMapping("/internal/member/{memberId}/active") public ResponseEntity<?> internalActive(@PathVariable Long memberId){return active(memberId);}
 @PostMapping public ResponseEntity<?> create(@RequestBody CreateSubscriptionRequest r){ if(r.memberId()==null||r.planId()==null)return ResponseEntity.badRequest().body(Map.of("message","memberId and planId are required")); if(!memberExists(r.memberId()))return ResponseEntity.status(404).body(Map.of("message","Member not found")); Plan p=plans.findById(r.planId()).orElse(null); if(p==null)return ResponseEntity.status(404).body(Map.of("message","Plan not found")); LocalDate start=LocalDate.now(); Subscription s=new Subscription();s.setMemberId(r.memberId());s.setPlanId(p.getId());s.setStartDate(start);s.setEndDate(start.plusDays(p.getDurationDays()));s.setStatus("ACTIVE");return ResponseEntity.status(201).body(subs.save(s)); }
 @PostMapping("/{id}/renew") public ResponseEntity<?> renew(@PathVariable Long id){return subs.findById(id).map(s->{Plan p=plans.findById(s.getPlanId()).orElse(null);if(p==null)return ResponseEntity.status(404).body(Map.of("message","Plan not found"));LocalDate base=s.getEndDate().isAfter(LocalDate.now())?s.getEndDate():LocalDate.now();s.setEndDate(base.plusDays(p.getDurationDays()));s.setStatus("ACTIVE");return ResponseEntity.ok(subs.save(s));}).orElse(ResponseEntity.notFound().build());}
 private boolean memberExists(Long id){try{rb.build().get().uri("http://MEMBER-SERVICE/internal/members/{id}",id).retrieve().toBodilessEntity();return true;}catch(Exception e){return false;}}
 public record CreateSubscriptionRequest(Long memberId,Long planId){}
}
